### ISSUE TITLE
Mysterious crash involving magically appearing granite wall

### ISSUE THREAD

**Issue by ShimmerFairy** [angband/angband#4417] opened 2020-05-22 03:54 UTC
I've been having occasional crashes with Angband 4.2.0 on my Gentoo Linux computer for a short while now, and since there are no real debug options, I haven't been able to get any real info on what's going on (and where there is a crash message, the SDL1 frontend quitting immediately means I can't actually read what's going on).

The attached save file is from the one time I noticed something after loading up post crash. I entered the small room my character is in and walked a few steps in before the game crashed. When I loaded back up, I noticed the entrance I came through had been blocked up with a granite wall that obviously wasn't there before the crash. (My character is positioned so that the wall tile in question is immediately south of me; it should be obvious the hallway that led me to this area.)

Considering it took a few steps into the area before the game freaked out, I wonder if the way the game handles the light my character is casting is involved, like maybe the game got confused about that tile when my character stopped casting light on it. (That's just a complete guess though, I have no clue how the code works.)

I don't know if all the crashes come from the same place this one does, but I'm hoping it is.

[crashing_save.tar.gz](https://github.com/angband/angband/files/4665950/crashing_save.tar.gz)

**Comment by NickMcConnell** [comment] 2020-05-22 04:04
Thanks for the report; this is actually a known bug (#4194) which is fixed in the current [development version](http://rephial.org/nightlies).  It's caused by the block fall trap, which makes a granite wall form behind you after you step off it.
Version 4.2.1 (with that and other fixes and improvements) should be out in the next week or two.

**Closed by NickMcConnell** 2020-05-22 04:04 UTC
Labels: R: duplicate
