### ISSUE TITLE
Stuck inside "Single Combat" cell

### ISSUE THREAD

**Issue by mishaneah** [angband/angband#4249] opened 2020-01-19 19:41 UTC
Version 4.2.0-dirty
Player used spell "Single Combat: with a greater rotting quylthulg. Greater rotting quylthulg blinks during combat but does not move. Killing greater rotting quylthulg does not return player to map. Stuck inside cell, alone with my thoughts. 
<img width="670" alt="Screen Shot 2020-01-19 at 11 39 46 AM" src="https://user-images.githubusercontent.com/60074839/72687204-72a08900-3ab0-11ea-8397-6e7d950fb967.png">

**Comment by NickMcConnell** [comment] 2020-01-19 19:57
Yep, that's a bug, the blink shouldn't have worked.

**Comment by mishaneah** [comment] 2020-01-20 01:03
Attached is the character file which can reliably reproduce the issue.
[djcakepop.zip](https://github.com/angband/angband/files/4084026/djcakepop.zip)

**Comment by mishaneah** [comment] 2020-01-20 03:10
Using Word of recall spell from within cell causes Angband to crash once yanked. (MacOS 10.14.6)

**Comment by NickMcConnell** [comment] 2020-01-20 04:34
Excellent, thanks.

**Comment by NickMcConnell** [comment] 2020-05-17 02:45
It turns out that the problem is that this savefile has a bad list of saved levels.  I cannot see what has caused this, and the savefile doesn't really give any information about how the list got into the state it is in.  So I've reached the point where I don't think it's worth me spending any more time on this; I'll leave the bug open, but set it to the Ongoing milestone in case this issue comes up again.

**Comment by NickMcConnell** [comment] 2021-07-18 21:06
Still happening as of cc3d9401b (see [this post](http://angband.oook.cz/forum/showpost.php?p=154451&postcount=155)).

**Comment by backwardsEric** [comment] 2021-07-19 16:47
While testing #4918 , my save file reached a state where killing the monster in the arena didn't return the player to the original cave.  Somehow, the names of the chunks in the chunk list were "Town", "Town", and "Town known".  I don't know how that happened, but that meant that the lookup for the original level by name would fail, and the arena would be recreated.

I don't know if that would explain the other reports of getting stuck in the arena, but one thing to look at would be if there's a way the chunk names wouldn't be properly handled on a save followed by a load.

**Comment by backwardsEric** [comment] 2021-07-19 17:12
In that chunk list with "Town", "Town", and "Town known", all three had depths of zero.  The first was 22 grids high and 66 wide.  The last two were 53 grids high and 158 wide.

**Comment by backwardsEric** [comment] 2021-07-19 18:14
#4919 is one way to prevent getting to a chunk list with "Town", "Town", and "Town known".

**Comment by NickMcConnell** [comment] 2021-07-19 20:38
> While testing #4918 , my save file reached a state where killing the monster in the arena didn't return the player to the original cave. Somehow, the names of the chunks in the chunk list were "Town", "Town", and "Town known". I don't know how that happened, but that meant that the lookup for the original level by name would fail, and the arena would be recreated.
> 
> I don't know if that would explain the other reports of getting stuck in the arena, but one thing to look at would be if there's a way the chunk names wouldn't be properly handled on a save followed by a load.

I have definitely found this with savefiles I've been fixing, so this is a good chance to be a fix for at least some of the occurrences, I think.

**Comment by backwardsEric** [comment] 2021-10-17 01:09
[This](http://angband.oook.cz/forum/showpost.php?p=155804&postcount=122) is an instance of a crash upon entry to the single combat arena rather than getting stuck inside (the reported version is Angband 4.2.3).  Apparently p->upkeep->health_who was NULL at the entry to arena_gen().  It's not clear how that happened:  all paths through target acquisition appear to call health_track().

**Comment by backwardsEric** [comment] 2021-10-17 01:23
lldb on the 4.2.3 Mac executable.  `disas -n arena_gen` reports the disassembly for all of arena_gen().  In that is

```
angband[0x10003111e] <+174>: callq  0x100099560               ; player_place
angband[0x100031123] <+179>: movslq 0x10(%r15), %rax
angband[0x100031127] <+183>: imulq  $0x1a0, %rax, %rdi        ; imm = 0x1A0
angband[0x10003112e] <+190>: addq   0x68(%rbx), %rdi
angband[0x100031132] <+194>: movl   $0x1a0, %edx              ; imm = 0x1A0 
angband[0x100031137] <+199>: movq   %r15, %rsi
angband[0x10003113a] <+202>: callq  0x1001058b2               ; symbol stub for: memcpy
```

The second line there matches the +179 offset for the program location when the segmentation fault occurred.  That appears to be dereferencing mon to get the value for mon->midx when setting up the arguments for memcpy().

**Comment by backwardsEric** [comment] 2021-10-23 01:54
With regard to #5106 , it looks like one path that could have caused call(s) to format() and overwritten the known level name is this:   one of restore_monsters()'s calls to mon_dec_timed() ends up triggering monster_revert_shape() for something that changed shape to a monster with PASS_WALL and that monster needs an emergency teleport to get out of the wall it's in; the teleport triggers handle_stuff() which has the opportunity to call format() via one the calls in ui-display.c, assembling the monster lore description for the monster lore subwindow, or assembling the equipment list (equip_mention() can call format()) for the equipment subwindow.

**Comment by NickMcConnell** [comment] 2021-12-18 00:43
Note the latest progress on this in #5184, but even the fact that there is still work being done on this means I think this should stay open for now.

**Comment by backwardsEric** [comment] 2023-08-20 18:27
With more than a year and a half since the last change for this problem and no new reports of trouble while 4.2.4 was available, is it time to close this?

**Comment by NickMcConnell** [comment] 2023-08-20 20:08
Yep, I think you fixed it.

**Closed by NickMcConnell** 2023-08-20 20:08 UTC
Labels: T: bug
