### ISSUE TITLE
4.2.1 Crash on OSX 10.15.4

### ISSUE THREAD

**Issue by davemcwish1** [angband/angband#4432] opened 2020-06-04 21:12 UTC
I tried compiling the master branch this on osx 10.15.4 but on trying to run it generates a crash report, attached. I also get the same if I use the pre-build binary of 4.2.0. The 4.1.3 pre-built binary runs ok though.

dave
[crash_report.txt](https://github.com/angband/angband/files/4732736/crash_report.txt)

**Comment by NickMcConnell** [comment] 2020-06-05 00:42
The report indicates an error in parsing ego_item.txt.  You don't have a version of this file in your user directory (~/Documents/Angband) do you?

**Comment by kusunosetoru** [comment] 2020-06-05 13:29
This can be reproduced by changing an item: line's sval column to reference
a non-existent object. This makes lookup_sval() returns a negative value, and
then lookup_kind() returns NULL, making an access to kidx member variable
through a NULL pointer.

I made a pull request #4434 that addresses this problem.

**Comment by davemcwish1** [comment] 2020-06-05 19:20
> The report indicates an error in parsing ego_item.txt. You don't have a version of this file in your user directory (~/Documents/Angband) do you?

@NickMcConnell The file does exist in the package (under Contents/Resources/lib/gamedata).

There are some differences between 4.2.1 and 4.1.3 e.g.

4.2.1:-
```
name:of the Haradrim
info:20000:30
alloc:5:20 to 127
combat:d5:d5:0
item:bow:Light Crossbow
flags:IGNORE_ACID | IGNORE_FIRE
values:MIGHT[1] | SHOTS[2d3]
min-values:MIGHT[1] | SHOTS[2]
```

4.1.3
```
name:of the Haradrim
info:20000:30
alloc:5:20 to 127
combat:d5:d5:0
item:bow:Light Crossbow
flags:IGNORE_ACID | IGNORE_FIRE
values:MIGHT[1] | SHOTS[1]
min-values:MIGHT[1] | SHOTS[1]
```
Is this the parse error ? (the 2d3 in the example above?

**Comment by NickMcConnell** [comment] 2020-06-05 21:51
The crash is almost certainly the issue that the pull request addresses.  So that means it must be an error in the item: line.  The puzzling part is why you're getting this and apparently no-one else is.  Having an old ego_item.txt in your user directory was one way I thought of that could explain that, but there may be others.
I'll try and reproduce it.

**Comment by davemcwish1** [comment] 2020-06-05 22:26
No need @NickMcConnell . I just reread your prior note and did find a copy of ego_item.txt buried away under ~/Documents/Angband. Once I removed I was able to build the cocoa front end and it runs file, although wont import my 4.13 saved character; that's no biggie. I found that I had a lot of other files indeed the whole /lib/gamedata folder so why would  ego_item.txt throw the parse error is that because it's the only one whose structure has changed between 4.1.3 and now?

**Comment by NickMcConnell** [comment] 2020-06-05 22:47
It's because it references object names read from object.txt, and there was a name change - Pseudo-Dragon Scale Mail became Shining Dragon Scale Mail.  So when the ego_item.txt parser reads the Pseudo-Dragon Scale Mail line from the old file, it tries to look up that objecvt and then throws an error when it can't find it.
I think we're all sorted here, so I'll close this now.

**Closed by NickMcConnell** 2020-06-05 22:47 UTC
