### ISSUE TITLE
Mac OS Mojave Crash Angband 4.2.0-dirty, built Aug 16 2019

### ISSUE THREAD

**Issue by willhartung** [angband/angband#4409] opened 2020-05-11 15:47 UTC
I don't think this has anything specific to do with Mojave.

Simply, while heading down a hall towards some Cold Hounds, the process crashes out.

Attached in a Apple crash dump report, and the save file (Tholon.zip). 

I go down, kill the red dragon, then up and to the left to kill the Unique, then I started heading east, down a long hall. I encountered a couple of Frost Giants, and I was getting cold breathed upon. Then, it just suddenly crashed. It seems from the crash dump that it's a monster trying to pick something up.

This happened to me twice.

[Tholon.zip](https://github.com/angband/angband/files/4610630/Tholon.zip)
[crash.txt](https://github.com/angband/angband/files/4610609/crash.txt)

**Comment by NickMcConnell** [comment] 2020-05-11 21:34
OK, I repeated your instructions as far as killing Uldor (also killing a nruling on the way), but when I went down the hall there were no frost giants and nothing breathing, but there were some creeping adamantite coins.
As you say, the crash looks like a monster was trying to pick up an object, but then there was something wrong with the object.  There is nothing obviously wrong with the code there, so I think the problem with the object must have already happened.  
I am running in the latest development version, so it's possible whatever caused the issue is already fixed; also I am probably not repeating your sequence of events properly.  Is there a chance you could get me a savefile from closer to the crash?

**Comment by backwardsEric** [comment] 2020-05-12 06:29
I was able to reproduce this from the save file (using the latest nightly, custom compiled on Mac OS X Mojave).  The cold hounds killed a mimic at (129,22) which leads to a dangling object reference.

**Comment by NickMcConnell** [comment] 2020-05-12 07:38
Ahhh, nice

**Comment by NickMcConnell** [comment] 2020-05-12 07:40
I've had a feeling there was a bug in mimic objects for ages, but never been able to pin it down.  Obvious now I've seen it 😉

**Comment by NickMcConnell** [comment] 2020-05-17 07:41
Fixed in 8c1bd6538

**Closed by NickMcConnell** 2020-05-17 07:41 UTC
