### ISSUE TITLE
Missing door on town level

### ISSUE THREAD

**Issue by ArmiesAndCastles** [angband/angband#5098] opened 2021-10-16 08:36 UTC
![missing_door](https://user-images.githubusercontent.com/89977716/137580464-fb8962df-fdf5-4fe5-bc96-7f1014006ab5.png)

When the character can see a monster through a door on the town level, that door disappears. I've checked the last release version (4.2.3), and everything works fine there. The problem only exists on the current master branch.

I'll look into it today to try to find the possible cause.

**Comment by v-chirkov** [comment] 2021-10-16 19:21
I think the issue may have been introduced in c9e4c8b8486a843a154a9e6b1dd2eac7a2bd61af.

I should be able to solve it, but first I would like to speak with the contributor of c9e4c8b8486a843a154a9e6b1dd2eac7a2bd61af. Otherwise, it will take me some time to completely understand the code in cave-view.c.

**Comment by backwardsEric** [comment] 2021-10-16 22:35
I did confirm it happens in the latest master so you can ignore my prior question.   A change that resolves it is up as a pull request.

There's something in cave-view.c that's assuming the PROJECTABLE and LOS flags are interchangeable (my guess is that it's the los() call in update_view_one() since los() uses square_isprojectable() rather than square_allowslos()).  That hasn't been addressed in the pull request.

**Comment by v-chirkov** [comment] 2021-10-17 08:28
I can confirm that #5100 works. I still want to know what exactly in cave-view.c causes it. I'll work on it some more.

It's something about update_view_one(). You guessed right.

The shop entrances disappear after update_view_one() calls become_viewable(). Disabling become_viewable() stops entrances from disappearing but makes the monsters invisible.

In any case, #5100 works and is a good solution, for now.

**Comment by v-chirkov** [comment] 2021-10-17 12:44
I begin to doubt whether the problem is in cave-view.c. I changed update_view() in cave-view.c to make every square visible. This made it so, except for shop entrances (and certain monsters).

It seems as if something is overwriting square flags for shop entrances, using sqinfo_off(). This is done outside cave-view.c.

**Closed** 2021-10-19 10:05 UTC
Labels: C: Main game
